### ISSUE TITLE
Types with the same name

### ISSUE THREAD

**Issue by zdd248** [softwaremill/tapir#109] opened 2019-05-27 12:21 UTC
```
object Robot {
  case class Update(name: String)
}

object Nail {
  case class Update(size: Int)
}

val endpointRobot = endpoint.post
      .in("robot")
      .in(jsonBody[Robot.Update])

val endpointNail = endpoint.post
      .in("nail")
      .in(jsonBody[Nail.Update])
```
...
```
List(endpointRobot, endpointNail).toOpenAPI("RobotAndNail", "0.1").toYaml
```

`swagger.yaml`:

Added types: `Update1`, `Update2`

**But**, but everywhere is used only `Update2`
Should be and `Update1` and `Update2`

**Comment by adamw** [comment] 2019-05-27 19:15
I'm getting the following:

```
openapi: 3.0.1
info:
  title: RobotAndNail
  version: '0.1'
paths:
  /robot:
    post:
      operationId: postRobot
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Update'
        required: true
      responses:
        '200':
          description: ''
  /nail:
    post:
      operationId: postNail
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Update1'
        required: true
      responses:
        '200':
          description: ''
components:
  schemas:
    Update:
      required:
      - name
      type: object
      properties:
        name:
          type: string
    Update1:
      required:
      - size
      type: object
      properties:
        size:
          type: integer
```

I think that's correct?

**Comment by adamw** [comment] 2019-12-05 16:14
Closing as cannot reproducee

**Closed by adamw** 2019-12-05 16:14 UTC
