### ISSUE TITLE
Generate schema for enumeratums

### ISSUE THREAD

**Issue by jwluiten** [softwaremill/tapir#829] opened 2020-11-05 10:17 UTC
Tapir does not generate a schema for enums. In stead it describes the enum in any schema that uses it. When using `openapi-generator` to generate frontend code, I end up with multiple types for what essentially is the same enum.

#### Example
Using enumeratum I define the following enum:
```scala
sealed abstract class CountryCode extends EnumEntry

  object CountryCode extends Enum[CountryCode] {
    case object NL extends CountryCode with Uppercase
    case object BE extends CountryCode with Uppercase
    case object LU extends CountryCode with Uppercase

    override val values: IndexedSeq[CountryCode] = findValues
  }

  case class Example1(id: Int, countryCode: CountryCode)
  case class Example2(name: String, countryCode: CountryCode)
```

This generates the following:

```yaml
components:
  schemas:
    Example1:
      required:
      - id
      - countryCode
      type: object
      properties:
        id:
          type: integer
          format: int64
        countryCode:
          type: string
          enum:
          - NL
          - BE
          - LU
    Example2:
      required:
      - name
      - countryCode
      type: object
      properties:
        name:
          type: string
        countryCode:
          type: string
          enum:
          - NL
          - BE
          - LU
```

The enum essentially defines a new type. So I would prefer the following result, which would prevent generating multiple types for the same enum:

```yaml
components:
  schemas:
    CountryCode:
      type: string
      enum:
      - BE
      - NL
      - LU
    Example1:
      required:
      - id
      - countryCode
      type: object
      properties:
        id:
          type: integer
          format: int64
        countryCode:
          $ref: '#/components/schemas/CountryCode'
    Example2:
      required:
      - name
      - countryCode
      type: object
      properties:
        name:
          type: string
        countryCode:
          $ref: '#/components/schemas/CountryCode'
```

**Comment by xela85** [comment] 2020-11-05 17:54
I have already developed instances for enumeratum in my projects, this could be a good start for you : 
```
import enumeratum._
import enumeratum.values._
import sttp.tapir._

trait TapirCodecEnumeratum {
  // Regular enums

  implicit def validatorEnumEntry[E <: EnumEntry](implicit enum: Enum[E]): Validator[E] =
    Validator.enum(enum.values.toList, v => Some(v.entryName))

  implicit def schemaForEnumEntry[E <: EnumEntry]: Schema[E] =
    Schema(SchemaType.SString)

  implicit def plainCodecEnumEntry[E <: EnumEntry](implicit enum: Enum[E]): Codec.PlainCodec[E] =
    Codec.string
      .mapDecode { s =>
        enum
          .withNameOption(s)
          .map(DecodeResult.Value(_))
          .getOrElse(DecodeResult.Mismatch(s"One of: ${enum.values.map(_.entryName).mkString(", ")}", s))
      }(_.entryName)
      .validate(validatorEnumEntry(enum))
}
```

**Comment by adamw** [comment] 2020-11-06 07:18
@xela85 maybe you'd be able to use the provided integration, https://tapir.softwaremill.com/en/latest/endpoint/integrations.html#enumeratum-integration

That said, the issue is about generating a reusable component in the openapi schemas, which is slightly different from what you've posted

**Comment by xela85** [comment] 2020-11-06 09:54
Sorry, @jwluiten, I only read the title 😅. So the goal of this issue is to avoid the use of `SchemaType.SString` ? 
It seems to be a kind of `SCoproduct` which is not an object ?

**Comment by adamw** [comment] 2020-11-06 10:31
The goal is to generate enumeration schemas in `components` so that they can be reused (and reuse them) instead of as regular "exploded" fields. The tricky part is (a) capturing the name of the enumeartion and using it in the schema (b) deciding when to use a component, and when to use direct fields

**Comment by jwluiten** [comment] 2020-11-06 16:39
Thanks for re-opening. The essence of the issue is that if an enum is used in multiple components it should not be inlined but become a component itself.

**Comment by adamw** [comment] 2020-11-06 16:40
I closed by mistake, "Close with comment" instead of "Comment" :)

**Comment by adamw** [comment] 2021-04-02 18:59
Release in 0.18.0-M2

**Closed by adamw** 2021-04-02 18:59 UTC

**Comment by andyczerwonka** [comment] 2021-08-19 19:26
@adamw @jwluiten I might be missing something, but it looks like the Schema is not using the `entryName`. A common pattern is to [override the name](https://github.com/lloydmeta/enumeratum#manual-override-of-name), and it looks like it's being ignored.

**Comment by adamw** [comment] 2021-08-20 07:19
@andyczerwonka it's possible that something is missing there :) What would be `entryName` used for - documentation only, or also something else?

**Comment by andyczerwonka** [comment] 2021-08-20 12:35
@adamw In my particular use case, it's an integration / migration issue, so I was trying to align the enum values across two different sets of types.

**Comment by adamw** [comment] 2021-08-20 13:26
@andyczerwonka Hm ok, well then please open an issue so that this could be fixed for the future. Some reproducing code showing expected/actual output would be great :)

**Comment by andyczerwonka** [comment] 2021-08-23 15:54
@adamw I've [logged it as per your request](https://github.com/softwaremill/tapir/issues/1444).
