### ISSUE TITLE
iron-tapir not seeing any validation messages

### ISSUE THREAD

**Issue by jenwirth** [softwaremill/tapir#3296] opened 2023-11-03 07:37 UTC
Hi,

When using iron with tapir and the `tapir-iron`, we don't see any validation messages. I created a isolated project to investigate this further. 

The project is here: https://github.com/jenwirth/tapir-iron-problem

To run:

```shell
sbt reStart
```

There's a swagger ui at: http://localhost:7777/docs/

Using [httpie](https://httpie.io/):

- returns "Invalid value for: body (expected phoneNumber to match:…)"

```shell 
$ http POST ':7777/toto/vanilla' phoneNumber="1111111111"
```

- returns just "Invalid value for: body"

```shell 
$ http POST ':7777/toto/iron' phoneNumber="1111111111"
```

It seems the validation message is missing. But inside `sttp.tapir.codec.iron.TapirCodecIron`, it is creating an implicit `validatorForMatchesRegexpString` that used the standard `Validator.pattern` on the base type.

**Comment by jenwirth** [comment] 2023-11-06 09:42
Just noticed i did not commit/push the build files in the sample project

**Comment by amorfis** [comment] 2023-11-29 13:44
Hello @jenwirth !

I have just created PR to your repository where you have isolated the problem. Thank you very much for this code, it made all the investigation much easier! 

To solve it some customisation is needed. We differentiate between validation errors and decoding errors, but tools like `iron` blur this distinction. Validation error means we can create the instance of a case class or field, but it doesn't fit our requirements. `iron` makes it even impossible to create an instance. From the tapir point of view it is then undistinguishable from decoding error caused by e.g. corrupted JSON. 

Actually it's what `iron` does - it changes "it's a good type but invalid value" into "it's invalid type" on scala code level. When used to JSON decoding it does the same thing - changes "valid JSON but invalid values" into "invalid JSON" - that's why we need to use workarounds like custom exceptions to overcome this.

Hope this helps, happy coding with tAPIr!

**Comment by adamw** [comment] 2023-11-29 13:55
@amorfis Maybe we can translate an iron exception into a validation error? It's true that *validators* (their logic) is run on already constructed values, but I think e.g. the refined integration creates custom `ValidationError`s by hand

**Comment by adamw** [comment] 2023-11-29 14:03
Ah ok, maybe I don't understand what the problem is, sorry for interjecting :)

**Comment by amorfis** [comment] 2023-11-29 16:06
@jenwirth I have added another possible solution here: https://github.com/jenwirth/tapir-iron-problem/pull/2 This time I have not created custom `Codec` but custom error handler. Still `Reader` has to throw custom exception so we can match it in the error handler and this way we know it's `iron` validation error not e.g. corrupted JSON. Then error message is constructed based on the information from the exception.

Enjoy! :)

**Comment by amorfis** [comment] 2023-12-19 12:44
Closing this issue as the solution has been provided

**Closed by amorfis** 2023-12-19 12:44 UTC
