### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by przemekkwiecien1982** [softwaremill/tapir#2085] opened 2022-04-27 14:25 UTC
Tapir version: 0.19.0

Scala version: 2.13.7

**Describe the bug**

What is the problem?

Cannot use `paths` if using `auth.apiKey(anotherInput)` during authorisation. 
I need to validate path parameter. I want to do that as a part of shared secure partial endpoint.

Unfortunately following code
`.securityIn(auth.apiKey[List[String]](paths))`

Causes following exception:
`Api key authentication can only be read from headers, queries or cookies, not:  
        Vector(PathsCapture(sttp.tapir.Codec$$anon$4@316cda31,Info(None,List(),false,Vector())))`
 
**How to reproduce?**
Use `paths` in securityIn

Maybe you can provide code to reproduce the problem?
`    
endpoint  
        .securityIn(auth.apiKey[List[String]](paths))  
        .zServerSecurityLogic(securityLogic)  
`

**Additional information**
Your documentations says:
`The input is typically a header, cookie or a query parameter`
So there is no explicitly said that paths are prohibited.

**Comment by gaeljw** [comment] 2022-04-27 19:58
Do you really have API key in the path? I'm not sure there is a definitive definition to what is an API key but at least from OpenAPI perspective it cannot be in path: https://swagger.io/docs/specification/authentication/api-keys/

**Comment by przemekkwiecien1982** [comment] 2022-04-28 07:10
We are using REST api, where part of the path is resource. During the
authorisation process we need to confirm the user from request has the
right to reach the resource.

śr., 27 kwi 2022 o 21:59 Gaël Jourdan-Weil ***@***.***>
napisał(a):

**Comment by adamw** [comment] 2022-04-28 09:24
@przemekkwiecien1982 I don't think you need to wrap the input in an `auth` then. This wrapper is only for documentational purposes - and as @gaeljw OpenAPI doesn't allow path to be part of the api key. If you need this in your authorization logic, adding the input via `.securityIn(paths)` should be enough. Note, however, that this will consume the entire remaining path.

**Comment by adamw** [comment] 2022-04-29 10:27
Closing as I think this is not a bug, but if there are more problems please reopen

**Closed by adamw** 2022-04-29 10:27 UTC

**Comment by przemekkwiecien1982** [comment] 2022-04-29 10:42
Correct, this is a feature ;)
Thank you for such a fast help!

pt., 29 kwi 2022 o 12:28 Adam Warski ***@***.***> napisał(a):
