### ISSUE TITLE
Assertion Error

### ISSUE THREAD

**Issue by nolledge** [softwaremill/tapir#117] opened 2019-06-02 14:38 UTC
I get a very long error output during compile time and I cant figure out the reason. At some point it says what I think a relevant part could be:

[error] (api / Compile / compileIncremental) java.lang.AssertionError: assertion failed:
[error]   new SerialVersionUID(value = 5066590221178148012L)
[error]      while compiling: /Users/user/workspace/*/api/src/main/scala/com/*/api/http/definitions/Endpoints.scala
[error]         during phase: superaccessors
[error]      library version: version 2.12.8
[error]     compiler version: version 2.12.8

This is sorrounded by some other output I can make no sense with like : 

[error]
[error]   last tree to typer: Ident(x)
[error]        tree position: line 6 of /Users/user/workspace/*/api/target/scala-2.12/src_managed/main/sbt-buildinfo/BuildInfo.scala
[error]             tree tpe: Any
[error]               symbol: value x
[error]    symbol definition: x: Any (a TermSymbol)
[error]       symbol package: <none>
[error]        symbol owners: value x
[error]            call site: lazy value optionTypeclass$macro$1590 in package definitions
[error]
[error] == Source file context for tree position ==
[error]
[error]      3 import scala.Predef._
[error]      4
[error]      5 /** This object was generated by sbt-buildinfo. */
[error]      6 case object BuildInfo {
[error]      7   /** The value is "api". */
[error]      8   val name: String = "api"
[error]      9   /** The value is "0.0.1-buildlocal". */

Removing sbt-buildinfo plugin did not help...

I am using tapir 0.8.1

**Comment by nolledge** [comment] 2019-06-02 15:02
I think its somehow related to magnolia. Error out looks quite similar to https://github.com/propensive/magnolia/issues/154 but I cant figure out what I can do about it

**Comment by adamw** [comment] 2019-06-02 19:08
@nolledge yes, that's caused by magnolia. My comment on the issue you linked is exactly what you experience. Unfortunately I don't know of a fix, apart from finding the missing `SchemaFor` instance and creating an implicit value for it.

If you can share some of the code that fails (the data structures), maybe we could pinpoint what's missing.

**Comment by nolledge** [comment] 2019-06-03 09:58
Hi @adamw 
Thank you for bringing my attention to the data structure. The error was related to a response entity containing values of type "Byte".

This entity was wrapped inside a "response container" with mutliple layers. To give you an idea it looks something like this (it is a little reduced):

```
case class Response(
  apiVersion: String,
  id: String,
  method: String,
  data: ResponseData[A]
)

final case class ResponseData[A](
  currentItemCount: Int,
  items: Iterable[A]
)
````

When I call     

``.out(jsonBody[ResponseData[MyItem]]) ``
it will result in that very long error out. 
When I call ``.out(jsonBody[Response[MyItem]]) `` this will handle the underlying error and reduce it to:

```
[error] /Users/user/workspace/*/Endpoints.scala:34:18: magnolia.Deferred is used for derivation of recursive typeclasses
[error]     .out(jsonBody[Response[Myitem]])
[error]                  ^
[error] one error found
[error] (api / Compile / compileIncremental) Compilation failed
```

For both errors the reason was a property of type **Byte** inside the ``MyItem``

**Comment by adamw** [comment] 2019-06-03 10:27
Ah! I've added a schema (mapping to an integer) in 0.8.2, for `Byte`, see the linked commit.

**Comment by adamw** [comment] 2019-06-18 10:13
I'll reopen this as this is a common problem. The minimal test case I found is:

```
object Test6 extends App {

  class A
  case class B(a: A)
  case class C(bs: Iterable[B])

  implicitly[SchemaFor[C]]
}
```

gives:
```
[error] /Users/adamw/projects/tapir/playground/src/main/scala/tapir/example/Test6.scala:14:13: magnolia.Deferred is used for derivation of recursive typeclasses
[error]   implicitly[SchemaFor[C]]
[error]             ^
```

**Comment by poohsen** [comment] 2019-09-17 15:17
i see a similar error but with `call site: lazy value listTypeclass$macro$27 in package routing` .

it seems to be thrown off by a nested field whose type is defined in terms of a trait and an object, as opposed to the rest which use case classes. Should I open a new issue for it?

**Comment by adamw** [comment] 2019-09-17 15:28
@poohsen a small example to reproduce would be great :)

**Comment by poohsen** [comment] 2019-09-17 16:21
```
import io.circe._
import io.circe.generic.semiauto._
import tapir._
import tapir.json.circe._
import scala.language.higherKinds

final case class Enclosing(
  nested: Nested
)

trait Nested {
  def value: String
}

object Nested {
  def apply(value: String): Nested = new Nested {
    override def value: String = value
  }
}

object TapirApp extends App {

  implicit val NestedD: Decoder[Nested] =
    Decoder.decodeString.map(Nested.apply)
  
  implicit val NestedE: Encoder[Nested] =
    Encoder.encodeString.contramap(_.value)

  implicit val EnclosingE: Encoder[Enclosing] = deriveEncoder
  implicit val EnclosingD: Decoder[Enclosing] = deriveDecoder

  val api: Endpoint[Unit, Unit, List[Enclosing], Nothing] = endpoint.get
    .out(jsonBody[List[Enclosing]])

}
```

**Comment by poohsen** [comment] 2019-09-18 07:35
@adamw see above

**Comment by poohsen** [comment] 2019-09-26 08:49
@adamw when changing the output type from `List[Enclosing]` to `Enclosing` the behaviour changes and I get a warning about the Json code missing for `Enclosing`

**Comment by poohsen** [comment] 2019-09-26 11:01
Turns out this was my poor understanding of Tapir. I didn't know I needed a Schema on top of the Decoder and Encoder.

**Comment by adamw** [comment] 2019-09-26 11:19
@poohsen yes, you need it for the docs. Maybe we can make the documentation better in this regard - where were you looking for the information, and where would you expect it? :)

**Comment by poohsen** [comment] 2019-09-26 11:32
I took your teaser example as a starting point and tried to adapt it to one of our applications. I didn't take the approach of reading the docs first. That should've been the second step after I encountered issues, I guess. Still, there are two things to improve IMO.

First, when I used List as a container then the compilation crashes with a cryptic error that OP described. From that message it is absolutely not clear that a missing schema might be the problem.

Not sure why this is only happening for Lists but it is. Which brings me to the second improvement: When using Seq or Iterable instead, I get an error message that start with `Cannot find a codec for type` - and that was enough to confuse me. 
The weird List behaviour before and the missing codec message made me conclude that the error message can't be trusted so I did not expect its second part (`Is there an implicit schema for`)  to be a valuable clue.

**Comment by adamw** [comment] 2019-09-26 13:32
@poohsen the crash & cryptic error *is* of course a bug, however in Magnolia, so we'll  have to fix it there.

As for the cannot find a codec error - unfortunately that's the best that's possible using Scala's implicits; it's not possible to determine which component (json encoder/decoder, validator, schema) is missing.

**Comment by ewestern** [comment] 2019-11-15 19:37
I've run into this issue as well. 
Here's the output FWIW https://gist.github.com/ewestern/43fae1f866c519ddeebfe9d86e517a5f
Unlike others in this thread, it doesn't appear that I'm missing any Schema instances (at least that I can see), and the only container type I'm using is Vector. 
I'm certainly not missing a Schema instance for the data structure referred to in the `== Source file context for tree position ==` section.
Would definitely appreciate it if someone can find any hints in the error output.

**Comment by adamw** [comment] 2019-11-15 20:29
@ewestern can you narrow down the code which causes this to something that you can paste? would be great to get a reproducing example

**Comment by ewestern** [comment] 2019-11-15 20:50
@adamw Will try to. It's a decent-sized project, so I'll have to circle back a bit later.

**Comment by adamw** [comment] 2019-12-05 16:14
There's a chance this is fixed now with an updated Magnolia version.
Maybe somebody from the reporters could check?

**Comment by ewestern** [comment] 2020-01-13 13:01
@adamw 
Can confirm that I didn't get this error after using the latest version.
Thanks.

**Closed** 2022-02-15 14:04 UTC
