### ISSUE TITLE
[BUG] mapTo not working with Higher Kinded Types

### ISSUE THREAD

**Issue by pierangeloc** [softwaremill/tapir#2938] opened 2023-06-05 13:39 UTC
Tapir version: 1.4.0

Scala version: 2.13

**`mapTo` produces an error with Higher-Kinded Types**

What is the problem?

If I use `mapTo` with an output type that is a higher-kinded type, the compiler produces an error.
The equivalent hand-made `map(forward)(backward)` works instead

**To reproduce:**

This compiles successfully:
```scala
  case class UserResp(user: String, header1: Int, header2: Int)
  val testEndpoint = endpoint.get
    .in("user")
    .out(
      jsonBody[String]
        .and(header[Int]("X-Header-1"))
        .and(header[Int]("X-Header-2"))
        .mapTo[UserResp]
    )
```

This one doesn't compile and produces the following error:
```
The type of the tuple field doesn't match the type of the case class field (value user): String, A
[error]         .mapTo[UserResp[String]]
[error]               ^
```

```scala
  case class UserResp[A](user: A, header1: Int, header2: Int)
  val testEndpoint = endpoint.get
    .in("user")
    .out(
      jsonBody[String]
        .and(header[Int]("X-Header-1"))
        .and(header[Int]("X-Header-2"))
        .mapTo[UserResp[String]]
    )
```

On the other hand, I can map manually the tuple to the HKT, and this will compile:

```scala
  case class UserResp[A](user: A, header1: Int, header2: Int)
  val testEndpoint = endpoint.get
    .in("user")
    .out(
      jsonBody[String]
        .and(header[Int]("X-Header-1"))
        .and(header[Int]("X-Header-2"))
        .map(tuple => (UserResp.apply[String] _).tupled(tuple))(resp => (resp.user, resp.header1, resp.header2))
    )
```

**Additional information**

**Comment by adamw** [comment] 2023-06-09 07:56
Thanks for the report! I think it is a duplicate of https://github.com/softwaremill/tapir/issues/2555, so I'll close this one

**Closed by adamw** 2023-06-09 07:56 UTC
