### ISSUE TITLE
Can't use error types using Throwable

### ISSUE THREAD

**Issue by vilu** [softwaremill/tapir#129] opened 2019-06-09 08:51 UTC
I'm trying out a POC using Tapir. I'm trying to use an Error type. I would love to be able carry around a throwable. I realised that it does not work well because of the missing Schema for throwable. Is there a work around? Should there be one?

Wouldn't mind helping if necessary.

```
// This version does not work due to missing Schema for Throwable
//sealed abstract class AppError(val statusCode: Int, val message: Option[String], val cause: Option[Throwable]) extends Product with Serializable
sealed abstract class AppError(val statusCode: Int, val message: Option[String]) extends Throwable with Product
```

**Comment by adamw** [comment] 2019-06-09 11:38
The schema should correspond to how the `cause: Option[Throwable]` is serialised. E.g. if the cause is serialised to a `String`, then you need to define `implicit val schemaForThrowable = SchemaFor[Throwable](Schema.SString)`

 Are you using JSON to return error responses?

**Comment by vilu** [comment] 2019-06-09 11:44
Oh, ok!

Yes Json but, actually I wouldn’t even serialize the throwable, what would just be omitted.

**Comment by adamw** [comment] 2019-06-09 11:47
Ah. Well then I would just define the schema for `AppError`, which would omit the field (instead of relying on auto-derivation):

```
implicit val schemaForAppError = SchemaFor[AppError](SProduct(SObjectInfo("com.(...).AppError"), List(...), List("statusCode", ...)))
```

**Comment by vilu** [comment] 2019-06-09 12:02
Ok! Will try that. Thanks for the help and the work on the library.

**Comment by adamw** [comment] 2019-12-05 16:16
Closing as probably solved :)

**Closed by adamw** 2019-12-05 16:16 UTC
