### ISSUE TITLE
Investigate using Nothing instead of Unit as error type in Endpoint without errors

### ISSUE THREAD

**Issue by matwojcik** [softwaremill/tapir#126] opened 2019-06-07 11:53 UTC
When I have endpoint having no errors defined:
```scala
  val someEndpoint: Endpoint[String, Unit, String, Nothing] = endpoint.in("foo" / path[String]).out(plainBody[String])
```
I'd expect `E` of `Endpoint` to be `Nothing` instead of `Unit`, as there is no possible error to be returned from the endpoint. `Unit` indicate there is one of value `Unit`.

Ideally in such case I'd like to be able to pass function like `I => F[O]` instead of `I => F[Either[Nothing, O]]` to functions creating routes e.g. 

```scala 
def toRoute(logic: I => Future[Either[E, O]])
``` 
in TapirAkkaHttpServer

**Comment by matwojcik** [comment] 2019-06-07 11:54
Related gitter: https://gitter.im/softwaremill/tapir?at=5cf91a03b76eac527ab20bad
There was suggestion by @adamw that  https://github.com/functional-streams-for-scala/fs2/blob/0b5540381302a9ecd3d1aff0fa90f31c101f5a63/core/shared/src/main/scala/fs2/fs2.scala#L36 can help

**Comment by adamw** [comment] 2019-06-07 12:50
Reconstructing my previous train of thought, here's a couple of points to consider. An endpoint `Endpoint[I, E, O, S]` corresponds roughly to a function `I => Either[E, O]`.

For inputs, if there's "no input", we need a no-arg function: `() => Either[E, O]`. So the "empty input case" should be `Unit`, not `Nothing`.

What about a completely empty endpoint? Should it have type `Endpoint[Nothing, Nothing, Nothing, Nothing]`? But that would mean that an empty endpoint cannot be interpreted as a server (maybe that's a good thing?). However somehow I think I would expect an empty endpoint to correspond to a server which always replies with `200 OK`.

Maybe a good reasoning behind using `Unit`s is that there are *default* status codes - even without specifying anything, an empty endpoint with a `Left` result will return a `400 Bad Request`, while an empty endpoint with a `Right` result will give `200 OK`.

**Comment by matwojcik** [comment] 2019-06-07 13:16
Probably when it comes to input it is fine to have `Unit`, as having there `Nothing` would mean you can't pass any input as there is no instance of this type. Similar thing comes to Output.

My point is rather for having `E` being Nothing in this case.

**Comment by adamw** [comment] 2019-06-07 13:18
Right. It breaks the symmetry between the error and success outputs, though :)

**Comment by valenterry** [comment] 2019-06-25 04:48
I think it shows that the design of using two type parameters for output/errors is not the optimal design from a theoretical perspective (using `Unit` for no-input is fine though). Not being able to have a "correct" encoding of an endpoint that can only return "good" results is just one of the implications that follows from it.

An idea to deal with that in a better way would be to have a much more general notion of endpoint in terms of `Endpoint[I, O, S]` where it can be further constrained to e.g. `type EndpointWithError[I, E, O, S] = Endpoint[I, Either[E, O], S]` (with better names for the types).

If tapir aims to be a general purpose library, it might be a good choice to make the types more general and then offer functionality based on certain shapes. E.g. if I want to generate a swagger documentation and tapir needs the information if my output type is an error output or a "normal" output to generate it for me, then generating the swagger would only work on `EndpointWithError`, not on every `Endpoint`. Other modules/documentations might have more constrained or relaxed requirements.

**Comment by adamw** [comment] 2019-06-27 09:26
@valenterry Well, tapir is scoped for http, so while you are right that some endpoints won't be expressible (for example ones which never fail) - I think a pragmatic choice is to make it easy to work with separate error/success types; and still keep the API reasonably friendly.

Some alternate ideas (along the lines you posted) are also available here: https://tapir-scala.readthedocs.io/en/latest/design.html

Would you also see usages for other shapes than `Endpoint[I, O, S]` and `Endpoint[I, Either[E, O], S]`?

**Comment by valenterry** [comment] 2019-06-27 10:17
@adamw If typealiases like in my suggestion make the API less userfriendly (i.e. due to suboptimal inferance), then I definitely see that as a reason to stick with the current design. In the best case, it should be transparent to a user whether they use the current Endpoint or the `EndpointWithError` alias that I mentioned.

For the shapes - I actually wonder about the distinction a little bit. If we are talking about HTTP, there are actually not only "good" and "bad" responses. [The RFC defines 5 categories](https://tools.ietf.org/html/rfc7231#section-6). Maybe the mapping between good/bad and these categories might be intuitive in most cases but apart from that, I don't even know for what tapir uses this differentiation between good/bad.

On the other hand, when it comes to generating documentation like swagger, it might be important to make the distinction clear in the type if swagger uses that to display things a certain way. But then there is not only swagger right? Who knows what kind of distinctions we might need for other things.

Same for interpreting into servers: maybe http4s and akka-http only differentiate between good and bad, but I can imagine there might be servers that use more than 2 distinct types. E.g. to differentiate between fatal and non-fatal errors.

Just some ideas off my head though :)

**Comment by adamw** [comment] 2019-06-27 14:25
@valenterry I haven't tried the type-alias approach, but I suspect it might be more cumbersome to use, and the `Either` might surface more often that we would want to. But then again, somebody would have to try to say anything definitely.

There are 5 response categories in the RFC, but most commonly you only have success and error cases (the HTTP model in general has a lot of things which aren't used exactly as designed ;) ). So you have 2xx "success" responses, and 4xx/5xx error responses. 1xx are used by proxies etc., and 3xx as either "fixed" responses or alternatives to success ones, both of which can be expressed in tapir.

So in the end, I still think that in 99% of case you'll end up with an "error" case and a "success" case.

As for fatal/non-fatal errors in servers, you usually have a catch-all 500 response which just says "sth is wrong" + the error is logged/there's an alert etc.

But adding more cases is already possible - you can have a status-code-differentiated output. See the `oneOf` + `statusMapping` outputs.

**Comment by ghostdogpr** [comment] 2019-07-17 08:50
I'm trying out Tapir and just stumbled upon this. I'm using ZIO so I sometimes have some business logic returning a `UIO`, which forces me to do `.mapError(_ => ())` to transform the `Nothing` error into `Unit`.

**Comment by adamw** [comment] 2019-07-17 10:02
@ghostdogpr yes, well maybe `Endpoint[Unit, Nothing, Unit, Nothing]` as the default would be the answer here, but that would require some research

**Comment by kubukoz** [comment] 2019-08-03 00:08
It's worth pointing out that whereas this isn't that much of an issue server-side (because you can always make a UIO or another infallible type a fallible one), but it is on the client side.

When you make e.g. an sttp request from a tapir endpoint, you want to make sure you're handled all error cases, and if you have an endpoint that you're sure never fails (at least apart from exceptional situations, which you don't describe in your API documentation either), you want to see that in types. `Unit` as the default error type just doesn't make that work.

I'd opt for `Nothing` as the default error type.

**Comment by adamw** [comment] 2019-09-10 19:36
@kubukoz @ghostdogpr @matwojcik so creating a base-endpoint of type `Endpoint[Unit, Nothing, Unit, Nothing]` isn't that hard. But ... what next? What kind of API you would expect to get for the client & server side - anything special for these "infallible" endpoints, or would you be fine with using the general methods, that is ending up with `Either[Nothing, O]`?

**Comment by kubukoz** [comment] 2019-09-10 20:42
I’m fine with `Either[Nothing, O]`. That can be merged to O safely :)

**Comment by ghostdogpr** [comment] 2019-09-11 00:06
Same here 👍

**Comment by matwojcik** [comment] 2019-09-11 04:49
Yes, that's what seems best for me 😉 if so, would you introduce it right away or in some 1.0 future?

**Comment by adamw** [comment] 2019-09-11 11:43
Released in 0.11.0

One remaining problem is what to do in the client, if the output is void (`Nothing`), but the request failed. Currently you'll get an `IllegalStateException`, which is not optimal, but the client interpreter needs some work anyway (e.g. decoding faillures and up as exceptions as well).

**Closed by adamw** 2019-09-11 11:43 UTC

**Comment by matwojcik** [comment] 2020-02-25 11:35
@adamw is there any plan to make Nothing default error type in `endpoint` instead of `infallibleEndpoint`?

**Comment by adamw** [comment] 2020-02-27 12:57
@matwojcik didn't have such plans :) does the current setup (with a choice of endpoint/infallibleEndpoint) have some downsides?

**Comment by matwojcik** [comment] 2020-02-27 13:02
I just consider `Unit` as a failure as worse design than `Nothing` ;) Plus somehow I completely missed that it was already in `0.11` by the fact it is not like that by default ;) 

the api itself would be probably even nicer if for `Endpoint[I, Nothing, O, S]` you could create route by passing `F[O]` (of course one can do `.toRoute(f.map(_.asRight[Nothing]))` but still :) )

**Comment by adamw** [comment] 2020-02-27 13:04
@matwojcik well I don't know - the only solution I see is opening an issue to make it default and see what's the popular opinion after some time :)

we could have e.g. `.toInfallibleRoute` available only on infallible endpoints?
