### ISSUE TITLE
[BUG] Encoding example body value in openapi

### ISSUE THREAD

**Issue by kubinio123** [softwaremill/tapir#1840] opened 2022-02-08 11:39 UTC
Tapir version: master

When we change field names (via `@encodedName` for example) in our body model and add the example value to our endpoint it renders in swagger with class field names rather than with the encoded ones.

```
package sttp.tapir.examples

import akka.actor.ActorSystem
import akka.http.scaladsl.Http
import spray.json.DefaultJsonProtocol._
import spray.json._
import sttp.tapir.Schema.annotations.encodedName
import sttp.tapir._
import sttp.tapir.generic.auto._
import sttp.tapir.json.spray._
import sttp.tapir.server.akkahttp.AkkaHttpServerInterpreter
import sttp.tapir.swagger.bundle.SwaggerInterpreter

import scala.concurrent.duration._
import scala.concurrent.{Await, Future}

object EncodedNamesBody extends App {

  final case class MyBody(@encodedName("fileXXX") file: S3FileRequestInfo)

  object MyBody {
    implicit val rw: JsonFormat[MyBody] = jsonFormat1(MyBody.apply)
  }

  final case class S3FileRequestInfo(@encodedName("fileKeyXXX") fileKey: String, @encodedName("bucketXXX") bucket: String, accessKey: String, secretKey: String)

  object S3FileRequestInfo {
    implicit val rw: JsonFormat[S3FileRequestInfo] = jsonFormat4(S3FileRequestInfo.apply)
  }

  val ep = endpoint.get.in("file").in(jsonBody[MyBody].example(MyBody(S3FileRequestInfo("xxx", "xxx", "xxx", "xxx"))))

  val route = AkkaHttpServerInterpreter().toRoute(ep.serverLogicSuccess(_ => Future.unit))

  val swaggerUIRoute =
    AkkaHttpServerInterpreter().toRoute(
      SwaggerInterpreter().fromEndpoints[Future](List(ep), "Files", "1.0.0")
    )

  implicit val actorSystem: ActorSystem = ActorSystem()
  import actorSystem.dispatcher

  val routes = {
    import akka.http.scaladsl.server.Directives._
    concat(route, swaggerUIRoute)
  }

  val bindAndCheck = Http().newServerAt("localhost", 8080).bindFlow(routes).map { _ =>
    println("Press any key to exit ...")
    scala.io.StdIn.readLine()
  }

  // cleanup
  Await.result(bindAndCheck.transformWith { r => actorSystem.terminate().transform(_ => r) }, Duration.Inf)
}
```
more info in [gitter thread](https://gitter.im/softwaremill/tapir?utm_source=notification&utm_medium=email&utm_campaign=unread-notifications#:~:text=mdipirro%20Feb%2007%2016%3A47-,Hello,-%2C%20I%20have%20an%20endpoint%20that)

**Comment by adamw** [comment] 2022-02-14 15:55
Isn't this because of the json codec? If you want to customise a field name, you have to do this both in the json code, and in our schema (which is unfortunate, but the two are completely independent, which also has good sides ;) )

**Comment by kubinio123** [comment] 2022-02-15 07:53
Reporter from gitter was providing custom codec with changed names and worked around it by providing `encodedExample` explicitly on the `Schema` (I need to add it to the reproducer attached).

Anyway I looked into the `ExampleConverter` code and saw that we are only using `Codec` to convert input parameters like path, header or cookie. I thought we need to use `Codec` for body inputs as well there.

Or maybe we can `encode` it right away in `Atom` method where we have a `Codec` instance
`def example(t: T): ThisType[T] = copyWith(codec, info.example(t))` ?

**Comment by mdipirro** [comment] 2022-02-25 14:46
@adamw and @kubinio123 thanks for looking into this! The report on Gitter was mine, and I confirm I customized the JSON codec as well (I'm using Spray). 

In particular, my JSON formatter (extending `RootJsonFormat`) looked more or less like the following one:
```
override def write(obj: MyBody): JsValue = JsObject(
  "sourceFile" -> JsObject(
    "fileKey" -> JsString(obj.file.fileKey.value),
    "bucket" -> JsString(obj.file.bucket.value),
    "awsAccessKey" -> JsString(obj.file.accessKey),
    "awsSecretKey" -> JsString(obj.file.secretKey),
  )
)
```

I made sure the correct implicit was being used. I also confirm that `encodedExample` saved my day.

**Comment by adamw** [comment] 2022-04-29 12:35
So this either got fixed along the way, or my reproduction is wrong. Here's my code:

```scala
import sttp.tapir._
import sttp.tapir.docs.openapi.OpenAPIDocsInterpreter
import sttp.tapir.openapi.circe.yaml.RichOpenAPI
import spray.json.{JsObject, JsString, JsValue, JsonFormat, RootJsonFormat}
import sttp.tapir.json.spray._
import sttp.tapir.Schema.annotations.encodedName
import sttp.tapir.generic.auto._

object Test2 extends App {
  final case class MyBody(@encodedName("fileKeyXXX") fileKey: String)
  implicit val rw: JsonFormat[MyBody] = new RootJsonFormat[MyBody] {
    override def read(json: JsValue): MyBody = ???
    override def write(obj: MyBody): JsValue = JsObject(
      "sourceFile" -> JsObject(
        "fileKeyXXX" -> JsString(obj.fileKey)
      )
    )
  }
  val ep = endpoint.get.in("file").in(jsonBody[MyBody].example(MyBody("xxx")))
  val docs: String = OpenAPIDocsInterpreter().toOpenAPI(List(ep), "x", "1.0").toYaml
  println(docs)
}
```

The output seems correct:

```
openapi: 3.0.3
info:
  title: x
  version: '1.0'
paths:
  /file:
    get:
      operationId: getFile
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MyBody'
            example:
              sourceFile:
                fileKeyXXX: xxx
        required: true
      responses:
        '200':
          description: ''
        '400':
          description: 'Invalid value for: body'
          content:
            text/plain:
              schema:
                type: string
components:
  schemas:
    MyBody:
      required:
      - fileKeyXXX
      type: object
      properties:
        fileKeyXXX:
          type: string
```

Hence closing for now, please reopen if this is still an issue.

**Closed by adamw** 2022-04-29 12:35 UTC
