### ISSUE TITLE
Example for optional jsonBody is empty string

### ISSUE THREAD

**Issue by cornerman** [softwaremill/tapir#2802] opened 2023-03-22 12:11 UTC
Tapir version: 1.2.10

Scala version: 2.13.10

**Describe the bug**

If you have an optional jsonBody in your http request, where the example should be the `None` case. Then the example will be created as an empty string `""`. The generated openapi spec looks like this:

```json
  "post" : {
        ...,
        "requestBody" : {
          "content" : {
            "application/json" : {
              "example" : "",
              "schema" : {
                "$ref" : "#/components/schemas/PluginData"
              }
            }
          },
          "required" : false
        },
        ...
  }
```

But sending this empty string as the json body will fail to decode, because it either accepts an empty body or the object's json representation. An empty string is actually wrong.

**How to reproduce?**

An example endpoint looks like this:

`endpoint.in(jsonBody[Option[Something]]).example(None))`

**Additional information**

I have to admit that I am not entirely sure whether the generated openapi spec is actually wrong, or whether I interpret it wrongly.
When, e.g., using swagger-ui with this openapi spec, it will put the empty string `""` as an example payload and fail when trying it out.

**Comment by adamw** [comment] 2023-03-22 14:10
There's a test for that case:
https://github.com/softwaremill/tapir/blob/6004c64bfbd9ca8b1ce1b590b59bf4bc9c1cb537/tests/src/main/scala/sttp/tapir/tests/Basic.scala#L161
https://github.com/softwaremill/tapir/blob/c60774272c9add30e74d816db2a846a0084cd61f/server/tests/src/main/scala/sttp/tapir/server/tests/ServerBasicTests.scala#L303

In fact an empty body is an empty string, that is, there's no way to distinguish between "no body" and `""`

But as you are experiencing some problems, can you post a reproducing example? Which json library / server implementation?

**Comment by adamw** [comment] 2023-05-08 08:19
Closing due to lack of a reproducing example, please reopen if it happens again.

**Closed by adamw** 2023-05-08 08:19 UTC
