### ISSUE TITLE
derivedSchema does not use companion instance

### ISSUE THREAD

**Issue by perok** [softwaremill/tapir#435] opened 2020-02-20 09:58 UTC
When using derivedSchema to define the schema with additional changes the wrong instance seems to be cached in derviedSchema. When using derivedSchema again then the companion object instance is not used.

Issue is reproduced in #434.

**Comment by adamw** [comment] 2020-02-24 13:15
Is this an issue only for top-level values? 

I've tried adding:

```
case class Wrapper(td: TopData)

val schema1 = Schema.derivedSchema[Wrapper]
val schema2 = implicitly[Schema[Wrapper]]
```

and both return schemas where the `TopData` schema has `"Should see this"`.

**Comment by perok** [comment] 2020-02-26 12:17
Yeah, I think so. The issue though is that Tapir.jsonBody will trigger usage of Schema.derivedSchema thus forcing the issue.

**Comment by adamw** [comment] 2020-02-27 13:33
`Tapir.jsonBody` looks up an implicit codec, which is created using `TapirJsonCirce.encoderDecoderCodec` (for Circe), which looks up an implicit schema, without directly calling `Schema.derivedSchema`. Indeed, this works for me as expected:

```
import sttp.tapir.{CodecForOptional, CodecFormat, Schema}
import io.circe.generic.auto._
import sttp.tapir.json.circe._

object Test extends App {
  case class TopData(one: Int)
  object TopData {
    implicit val schema: Schema[TopData] =
      Schema.derivedSchema[TopData].description("Should see this")
  }

  val implicitSchema = implicitly[CodecForOptional[TopData, CodecFormat.Json, _]].meta.schema

  println(implicitSchema)
}
```

so I suspect you must be doing something else somewhere :)

**Comment by adamw** [comment] 2022-02-15 14:02
`.derivedSchema` always derives the schema, regardless of other existing implicit instances. Closing as this is not a bug.

**Closed by adamw** 2022-02-15 14:02 UTC
