### ISSUE TITLE
Endpoint with stringBody hang on request with no body provided

### ISSUE THREAD

**Issue by danslapman** [softwaremill/tapir#2133] opened 2022-05-18 10:25 UTC
Tapir version: 1.0.0-RC1

Scala version: 2.13.8

Any endpoint with a string body hangs when no body provided

What is the problem?

Just GET localhost:8080/test after running code below

Maybe you can provide code to reproduce the problem?

Here is simple ammonite script

```scala
import $ivy.`com.softwaremill.sttp.tapir::tapir-zio1-http-server:1.0.0-RC1`

import sttp.model.Header
import sttp.tapir.Codec
import sttp.tapir.CodecFormat
import sttp.tapir.server.ziohttp.ZioHttpInterpreter
import sttp.tapir.ztapir._
import zhttp.http.Http
import zhttp.http.Request
import zhttp.http.Response
import zhttp.service.Server
import zhttp.service.EventLoopGroup
import zhttp.service.server.ServerChannelFactory
import zio._


implicit val throwableCodec: Codec[String, Throwable, CodecFormat.TextPlain] =
    Codec.string.map[Throwable](new Exception(_: String))(_.toString)

val testEndpoint =
  endpoint.get
    .in("test")
    .in(stringBody)
    .errorOut(plainBody[Throwable])
    .out(stringBody)

val serverEndpoint = testEndpoint.zServerLogic[Any](body => ZIO.succeed(body))

val http = ZioHttpInterpreter().toHttp(serverEndpoint)

val server: ZManaged[EventLoopGroup with zhttp.service.ServerChannelFactory, Throwable, Server.Start] = Server(http).withPort(8080).make
 
val fullServer = server.provideLayer(EventLoopGroup.auto(0) ++ ServerChannelFactory.auto)

Runtime.default.unsafeRun(fullServer.useForever)
```

**Comment by adamw** [comment] 2022-05-19 06:17
I think the problem is that GET + body doesn't work, see: https://github.com/dream11/zio-http/issues/1221
This is fixed in zio-http but not yet released

**Comment by danslapman** [comment] 2022-05-19 07:03
Thanks for clarification, okay, 'll wait for next RC of zio-http :)

**Comment by danslapman** [comment] 2022-05-20 11:35
I tried vert.x instead of zio-http and got similiar results - request just hangs :( So, the problem might not be in zio-http

Just GET localhost:8080/test after running code below

```scala
import $ivy.`com.softwaremill.sttp.tapir::tapir-vertx-server:1.0.0-RC1`
import $ivy.`com.softwaremill.sttp.tapir::tapir-zio:1.0.0-RC1`
import $ivy.`ch.qos.logback:logback-classic:1.2.10`

import io.vertx.core.Vertx
import io.vertx.ext.web.Router
import sttp.tapir.plainBody
import sttp.tapir.query
import sttp.tapir.server.vertx.VertxZioServerInterpreter
import sttp.tapir.server.vertx.VertxZioServerInterpreter._
import sttp.tapir.ztapir._
import zio._

implicit val runtime = zio.Runtime.default

val responseEndpoint =
    endpoint
      .get
      .in("test")
      .in(stringBody)
      .out(stringBody)

val attach = VertxZioServerInterpreter().route(responseEndpoint.zServerLogic(body => UIO.succeed(body)))

runtime.unsafeRun {
  ZIO.scoped(
      ZIO
        .acquireRelease(
          ZIO
            .attempt {
              val vertx  = Vertx.vertx()
              val server = vertx.createHttpServer()
              val router = Router.router(vertx)
              attach(router)
              server.requestHandler(router).listen(8080)
            }
            .flatMap(_.asRIO)
        ) { server =>
          ZIO.attempt(server.close()).flatMap(_.asRIO).orDie
        }
        *> ZIO.never
    )
}
```

**Comment by adamw** [comment] 2022-05-20 12:12
With vertx, I'm getting a 500 and in the logs:

```
2022-05-20 14:11:18,726 [vert.x-eventloop-thread-0] ERROR io.vertx.ext.web.RoutingContext - Unhandled exception in router
java.lang.IllegalStateException: Request method must be one of POST, PUT, PATCH or DELETE to decode a multipart request
	at io.vertx.core.http.impl.Http1xServerRequest.setExpectMultipart(Http1xServerRequest.java:468)
	at io.vertx.ext.web.impl.HttpServerRequestWrapper.setExpectMultipart(HttpServerRequestWrapper.java:301)
	at io.vertx.ext.web.handler.impl.BodyHandlerImpl$BHandler.<init>(BodyHandlerImpl.java:184)
	at io.vertx.ext.web.handler.impl.BodyHandlerImpl.handle(BodyHandlerImpl.java:84)
	at io.vertx.ext.web.handler.impl.BodyHandlerImpl.handle(BodyHandlerImpl.java:44)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
	at io.vertx.ext.web.impl.RouterImpl.handle(RouterImpl.java:67)
	at io.vertx.ext.web.impl.RouterImpl.handle(RouterImpl.java:37)
	at io.vertx.core.http.impl.Http1xServerRequestHandler.handle(Http1xServerRequestHandler.java:67)
	at io.vertx.core.http.impl.Http1xServerRequestHandler.handle(Http1xServerRequestHandler.java:30)
	at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:50)
	at io.vertx.core.impl.DuplicatedContext.emit(DuplicatedContext.java:168)
	at io.vertx.core.http.impl.Http1xServerConnection.handleMessage(Http1xServerConnection.java:145)
	at io.vertx.core.net.impl.ConnectionBase.read(ConnectionBase.java:155)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:153)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
	at io.netty.handler.codec.http.websocketx.extensions.WebSocketServerExtensionHandler.channelRead(WebSocketServerExtensionHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.vertx.core.http.impl.Http1xUpgradeToH2CHandler.channelRead(Http1xUpgradeToH2CHandler.java:116)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:314)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:435)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.vertx.core.http.impl.Http1xOrH2CHandler.end(Http1xOrH2CHandler.java:61)
	at io.vertx.core.http.impl.Http1xOrH2CHandler.channelRead(Http1xOrH2CHandler.java:38)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

No idea what multipart is doing in that exception msg, but if I change the endpoint to `POST` it works. I guess they are following the rule that `GET`s shouldn't have a body :)

**Comment by adamw** [comment] 2022-06-06 10:42
Works fine in the latest release

**Closed by adamw** 2022-06-06 10:42 UTC
